version = 0.1
[default.deploy.parameters]
stack_name = "sam-postalcode-clustering"
resolve_s3 = true
s3_prefix = "sam-postalcode-clustering"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EventBusName=\"prod-daas-events-ml\" AccountEnv=\"Prod\""
image_repositories = ["PostalcodeClusteringFunction=910312087826.dkr.ecr.ap-northeast-2.amazonaws.com/sampostalcodeclusteringc50d00c3/postalcodeclusteringfunction836a4ceerepo"]
