name: cd-template

on:
  workflow_call:
    inputs:
      SLACK_TITLE:
        required: true
        type: string
      EVENT_BUS_NAME:
        required: true
        type: string
      SAM_CONFIG_FILE:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      SAM_S3:
        required: true
      ORGA_INFRA_SLACK_WEB_HOOK:
        required: true

jobs:
  ml-cluster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pyhton Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: AWS SAM Setup
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Build
        run: cd lambda/postalcode-clustering && sam build

      - name: SAM Deploy
        env:
          S3_BUCKET: ${{ secrets.SAM_S3 }}
          EVENT_BUS_NAME: ${{ inputs.EVENT_BUS_NAME }}
          ACCOUNT_ENV: ${{ inputs.SLACK_TITLE }}
          SAM_CONFIG_FILE: ${{ inputs.SAM_CONFIG_FILE }}
        run: cd lambda/postalcode-clustering && sam deploy --config-file $SAM_CONFIG_FILE

      - name: Slack Fail release
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: server-ops-dev
          SLACK_MESSAGE: ${{ inputs.SLACK_TITLE }} Cluster SAM deployment failed (${{github.job}})
          SLACK_TITLE: AWS SAM deploy
          SLACK_COLOR: "#FF0000"
          SLACK_USERNAME: Infra-noti-bot
          SLACK_WEBHOOK: ${{ secrets.ORGA_INFRA_SLACK_WEB_HOOK }}
          SLACK_ICON_EMOJI: ":bell:"
      
      - name: Slack Successful release
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_MESSAGE: ${{ inputs.SLACK_TITLE }} Cluster SAM deployment succeeded (${{ github.job }})
          SLACK_TITLE: AWS SAM deploy
          SLACK_USERNAME: Infra-noti-bot
          SLACK_WEBHOOK: ${{ secrets.ORGA_INFRA_SLACK_WEB_HOOK }}
          SLACK_ICON_EMOJI: ":bell:"